### ISSUE TITLE
It's invalid Find_Minimum_of_n_number.cpp

### ISSUE THREAD

**Issue by muhamdasim** [Afroz78692/hacktoberfest19#57]
Here is the correct solution.

`#include<stdio.h>
int main(){
	int n,i,min;
	scanf("%d",&n);
	int a[n];
	for(i=0;i<n;i++)
	{
	scanf("%d",&a[i]);
	}
	min=a[0];
	for(i=0;i<n;i++)
	{
		if(a[i]<min)
		{
		    min=a[i];
		}
	}
	printf("%d",min);
	
}`

**Comment by afroz23** [comment]
Good Work  :-)
